### PR TITLE
CONFIG: II-66 update serverspec to 2.35

### PR DESCRIPTION
**Pull request by k0da**
We want to have content_as_yaml, lets bump serverspec

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by sl4dy** [comment]
extended test - (cl-c3|k8s-el7|rat)

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by ytsarev** [comment]
Time to switch to Inspec dudes :)

**Pull request closed without merging**
