### PR TITLE
TRIVIAL: bundle facter gem

### PR DESCRIPTION
**Pull request by jan-cipa**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by Rohlik** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=serverspec-core-gate-PR78

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/serverspec-core-merge-compliance-check/10/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/compliance/job/serverspec-core-fossa-scanning-zuul-el7/3/ : FAILURE in 1m 07s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/serverspec-core-sonarqube-scan-zuul-gate/2/ : SUCCESS in 40s

**Pull request merged**
