### PR TITLE
CONFIG: SETI-3728 Bump version of package to 1.9.13-9

### PR DESCRIPTION
**Pull request by nhatking16591**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by caohhung** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/serverspec-core-merge-compliance-check/5/ : SUCCESS in 23s

**Pull request merged**
