### PR TITLE
TRIVIAL: tune for building on el9

### PR DESCRIPTION
**Pull request by jan-cipa**
adding rexml gem (not bundled anymore by default in ruby3)
change github url to clone directly from https

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by kristian-lesko** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=serverspec-core-gate-PR77

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/serverspec-core-merge-compliance-check/9/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/compliance/job/serverspec-core-fossa-scanning-zuul-el7/2/ : FAILURE in 1m 06s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/serverspec-core-sonarqube-scan-zuul-gate/1/ : SUCCESS in 43s

**Pull request merged**
